### ISSUE TITLE
Container core:  write script to assist updating derived repos to version 6

### ISSUE THREAD

**Issue by steve-fischer-200** [VEuPathDB/lib-jaxrs-container-core#16]
Details to follow...

**Comment by dmgaldi** [comment]
Here's the status as far as I can tell for the remaining services:

|Repo|Status|
|----|------|
|[service-osi-generator](https://github.com/VEuPathDB/service-osi-generator)|PR posted|
|[EdaUserService](https://github.com/VEuPathDB/EdaUserService)|Requires EdaCommon/FGPUtil update|
|[EdaSubsettingService](https://github.com/VEuPathDB/EdaSubsettingService)|Requires EdaCommon/FGPUtil update|
|[EdaDataService](https://github.com/VEuPathDB/EdaDataService)|Requires EdaCommon/FGPUtil update|
|[EdaMergingService](https://github.com/VEuPathDB/EdaMergingService)|Requires EdaCommon/FGPUtil update|
|[service-dataset-download](https://github.com/VEuPathDB/service-dataset-download)|Requires EdaCommon/FGPUtil update|
|[service-dataset-access](https://github.com/VEuPathDB/service-dataset-access)|TODO|

**Already Done Previously**
* [service-user-dataset-import](https://github.com/VEuPathDB/service-user-dataset-import)
* [service-multi-blast](https://github.com/VEuPathDB/service-multi-blast)
* [example-jaxrs-container-service](https://github.com/VEuPathDB/example-jaxrs-container-service)

**Comment by dmgaldi** [comment]
One idea is to extract the piece of FGPUtil that's using Jaxrs into a smaller versioned library. I'm not sure what the extent of the effort would be for something like that but otherwise the update will get pretty challenging

**Comment by dmgaldi** [comment]
Latest PRs to upgrade container core minor version to include some changes used by EdaCommon that are in master:
* https://github.com/VEuPathDB/EdaDataService/pull/164
* https://github.com/VEuPathDB/EdaSubsettingService/pull/62
* https://github.com/VEuPathDB/service-dataset-download/pull/4
* https://github.com/VEuPathDB/EdaMergingService/pull/8

**Comment by ryanrdoherty** [comment]
I believe this is complete.
