### ISSUE TITLE
Health endpoint should give some indication as to which DB(s) a service is connecting to.

### ISSUE THREAD

**Issue by Foxcapades** [VEuPathDB/lib-jaxrs-container-core#3]
Presently it gives a vague answer such as "user-db" or "acct-db".  It should include some information (probably not the actual db name) that can be used to determine what site's DB is in use.

**Comment by Foxcapades** [comment]
> probably not the actual db name

Perhaps this is just being overly cautious?

**Comment by Foxcapades** [comment]
The easiest way to implement this would be to examine the DataSource object that is handed to the Dependency instance to get the connection info if possible.

**Comment by steve-fischer-200** [comment]
i wonder about this.  this seems like it is part of the service's configuration.  there is a lot of config info, and i don't know we expect the health endpoint to describe it.

we now have a confluence document describing how to fine out config info for services.  does that suffice?

**Comment by Foxcapades** [comment]
Yeah, that should suffice.  When  this ticket was created, I don't believe the info we need was available through `pconf`, but since it is now available to us, this is, at best, very low priority.
